"""Backend foundation for future GTT-managed GCSIM engine lifecycle."""

from .artifact_build import GcsimBuildArtifactResult, build_gcsim_artifact
from .artifact_runner import (
    GcsimArtifactRunResult,
    GcsimResultSummary,
    parse_gcsim_result_payload,
    run_active_gcsim_artifact,
)
from .abyss_wave_scenario import (
    AbyssEnemyIdentityCandidate,
    AbyssEnemyTypeMapping,
    AbyssEnemyTypeMappingRecord,
    AbyssEnemyTypeResolution,
    AbyssWaveScenarioAudit,
    AbyssWaveScenarioBuildResult,
    abyss_enemy_name_candidates,
    abyss_enemy_identity_candidates,
    audit_abyss_wave_scenario,
    build_abyss_wave_scenario_payload,
    load_enemy_type_mapping_from_json,
    write_abyss_wave_scenario_payload,
)
from .enemy_type_registry import (
    GcsimEnemyNameCandidate,
    GcsimEnemyTypeMatch,
    GcsimEnemyTypeRegistry,
    load_default_gcsim_enemy_type_registry,
    load_gcsim_enemy_type_registry_from_go_source,
    normalize_gcsim_enemy_name,
)
from .engine_store import (
    GCSIM_ENGINE_MANIFEST_SCHEMA_VERSION,
    GcsimEngineStorePruneResult,
    GcsimEngineInstallation,
    GcsimEngineManifest,
    GcsimEngineStore,
    GcsimEngineUpdateResult,
    GcsimPatchResult,
    OverlayPatchBackend,
    PatchBackend,
)
from .runtime_probe import (
    GcsimGoBuildCacheCleanupResult,
    GcsimRuntimeProbeResult,
    cleanup_go_build_cache,
    run_gcsim_runtime_probe,
)
from .patch_backends import GitApplyPatchBackend

__all__ = [
    "GCSIM_ENGINE_MANIFEST_SCHEMA_VERSION",
    "GcsimArtifactRunResult",
    "GcsimBuildArtifactResult",
    "GcsimEngineInstallation",
    "GcsimEngineManifest",
    "GcsimEngineStorePruneResult",
    "GcsimEngineStore",
    "GcsimEngineUpdateResult",
    "GcsimGoBuildCacheCleanupResult",
    "GcsimPatchResult",
    "GcsimResultSummary",
    "OverlayPatchBackend",
    "PatchBackend",
    "GitApplyPatchBackend",
    "GcsimRuntimeProbeResult",
    "AbyssEnemyIdentityCandidate",
    "AbyssEnemyTypeMapping",
    "AbyssEnemyTypeMappingRecord",
    "AbyssEnemyTypeResolution",
    "AbyssWaveScenarioAudit",
    "AbyssWaveScenarioBuildResult",
    "GcsimEnemyNameCandidate",
    "GcsimEnemyTypeMatch",
    "GcsimEnemyTypeRegistry",
    "abyss_enemy_name_candidates",
    "abyss_enemy_identity_candidates",
    "audit_abyss_wave_scenario",
    "build_abyss_wave_scenario_payload",
    "load_default_gcsim_enemy_type_registry",
    "load_gcsim_enemy_type_registry_from_go_source",
    "load_enemy_type_mapping_from_json",
    "normalize_gcsim_enemy_name",
    "parse_gcsim_result_payload",
    "run_active_gcsim_artifact",
    "cleanup_go_build_cache",
    "run_gcsim_runtime_probe",
    "write_abyss_wave_scenario_payload",
    "build_gcsim_artifact",
]
