"""Backend foundation for future GTT-managed GCSIM engine lifecycle."""

from importlib import import_module as _import_module

from .patch_backends import GitApplyPatchBackend


_LAZY_MODULE_EXPORTS: dict[str, tuple[str, ...]] = {
    ".artifact_build": (
        "GcsimBuildArtifactResult",
        "build_gcsim_artifact",
    ),
    ".artifact_runner": (
        "GcsimArtifactRunResult",
        "GcsimResultSummary",
        "parse_gcsim_result_payload",
        "run_active_gcsim_artifact",
    ),
    ".artifact_set_catalog": (
        "GcsimArtifactSetCapability",
        "GcsimArtifactSetCatalog",
        "GcsimArtifactSetCatalogError",
        "load_gcsim_artifact_set_catalog",
    ),
    ".abyss_wave_scenario": (
        "AbyssEnemyIdentityCandidate",
        "AbyssEnemyTypeMapping",
        "AbyssEnemyTypeMappingRecord",
        "AbyssEnemyTypeResolution",
        "AbyssWaveScenarioAudit",
        "AbyssWaveScenarioBuildResult",
        "abyss_enemy_name_candidates",
        "abyss_enemy_identity_candidates",
        "audit_abyss_wave_scenario",
        "build_abyss_wave_scenario_payload",
        "load_enemy_type_mapping_from_json",
        "write_abyss_wave_scenario_payload",
    ),
    ".enemy_type_registry": (
        "GcsimEnemyNameCandidate",
        "GcsimEnemyTypeMatch",
        "GcsimEnemyTypeRegistry",
        "load_default_gcsim_enemy_type_registry",
        "load_gcsim_enemy_type_registry_from_go_source",
        "normalize_gcsim_enemy_name",
    ),
    ".engine_store": (
        "GCSIM_ENGINE_MANIFEST_SCHEMA_VERSION",
        "GcsimEngineStorePruneResult",
        "GcsimEngineInstallation",
        "GcsimEngineManifest",
        "GcsimEngineStore",
        "GcsimEngineUpdateResult",
        "GcsimPatchResult",
        "OverlayPatchBackend",
        "PatchBackend",
    ),
    ".runtime_probe": (
        "GcsimGoBuildCacheCleanupResult",
        "GcsimRuntimeProbeResult",
        "cleanup_go_build_cache",
        "run_gcsim_runtime_probe",
    ),
    ".farming_search": (
        "SURVIVOR_REQUIRED_PROFILE",
        "CandidateEvaluation",
        "FourPieceCandidateCoverage",
        "FourPieceSetState",
        "ScreeningSurvivorBudget",
        "SearchSurvivor",
        "SearchWearer",
        "SetProfileCandidate",
        "StatAxis",
        "StatDelta",
        "StatProfile",
        "StatProfileBank",
        "StatWeight",
        "SurvivorSelectionResult",
        "WearerProfileSelection",
        "build_four_piece_candidate_coverage",
        "generate_stat_profile_bank",
        "select_screening_survivors",
    ),
    ".farming_profile_config": (
        "DEFAULT_FIXED_SUBSTATS_COUNT",
        "DEFAULT_INDIVIDUAL_LIQUID_CAP",
        "DEFAULT_TOTAL_LIQUID_SUBSTATS",
        "FOUR_STAR_LIQUID_ROLL_PENALTY",
        "FOUR_STAR_RARITY_PENALTY",
        "GCSIM_AUTOMATIC_RESPONSE_STAT_AXES",
        "GCSIM_BALANCED_REFERENCE_WEIGHTS",
        "GCSIM_SCREENING_PROFILE_CONTRACT",
        "GCSIM_SCREENING_STAT_AXES",
        "GCSIM_SUBSTAT_ROLL_VALUES",
        "GcsimScreeningCharacterProfile",
        "GcsimScreeningConfigRenderResult",
        "GcsimScreeningProfileError",
        "GcsimScreeningStatAllocation",
        "GcsimSubstatRollCount",
        "allocate_gcsim_screening_substats",
        "apply_gcsim_screening_runtime_options",
        "build_default_gcsim_screening_profile_bank",
        "build_gcsim_screening_investment_signature",
        "render_gcsim_screening_profile_config",
    ),
    ".farming_evaluator": (
        "CandidateKey",
        "DEFAULT_GCSIM_FARMING_CANDIDATE_TIMEOUT_SECONDS",
        "DEFAULT_GCSIM_FARMING_RUNS_DIR",
        "GCSIM_FARMING_EVALUATION_CACHE_MODE",
        "GCSIM_FARMING_EVALUATION_CONTRACT",
        "GcsimFarmingBatchResult",
        "GcsimFarmingBatchStatus",
        "GcsimFarmingEvaluationError",
        "GcsimFarmingEvaluationIdentity",
        "GcsimFarmingEvaluationRequest",
        "GcsimFarmingEvaluationResult",
        "GcsimFarmingEvaluationScheduler",
        "GcsimFarmingEvaluationSession",
        "GcsimFarmingEvaluationStatus",
        "GcsimFarmingSchedulerBudget",
        "FarmingCompletionCallback",
        "freeze_gcsim_farming_environment",
        "normalize_gcsim_farming_frozen_environment",
        "prepare_bound_gcsim_farming_evaluation",
        "prepare_bound_gcsim_farming_joint_evaluation",
        "run_gcsim_farming_evaluations",
    ),
    ".farming_team_search": (
        "FULL_TEAM_COMPOSER_PROVENANCE_SCHEMA",
        "FullTeamBatchSimulator",
        "FullTeamCandidatePool",
        "FullTeamComposerBudget",
        "FullTeamComposerError",
        "FullTeamComposerRequest",
        "FullTeamComposerResult",
        "FullTeamEvaluationRecord",
        "FullTeamPhysicalState",
        "FullTeamProbeState",
        "FullTeamSimulationMetrics",
        "FullTeamSimulationRequest",
        "PhysicalKey",
        "ProbeKey",
        "TEAM_SEARCH_BUDGET_EXHAUSTED",
        "TEAM_SEARCH_CANCELLED",
        "TEAM_SEARCH_COMPLETED",
        "TEAM_SEARCH_DEADLINE_REACHED",
        "TEAM_SEARCH_DOMAIN_EXHAUSTED",
        "TEAM_SEARCH_NO_SUCCESS",
        "TEAM_SEARCH_POLICY_EXHAUSTED",
        "TEAM_SEARCH_ROUND_LIMIT_REACHED",
        "TEAM_SIM_CANCELLED",
        "TEAM_SIM_FAILED",
        "TEAM_SIM_PASSED",
        "TEAM_SIM_TIMEOUT",
        "compose_full_team_four_piece_states",
    ),
    ".farming_pipeline": (
        "GCSIM_FARMING_PIPELINE_CONTEXT_SCHEMA",
        "GCSIM_FARMING_STATIC_TARGET_HP",
        "GcsimFarmingFullTeamBatchSimulator",
        "GcsimFarmingMaterializedProbe",
        "GcsimFarmingPipelineError",
        "GcsimFarmingScreeningFidelity",
        "LayoutCatalog",
        "build_gcsim_farming_evaluation_context_sha256",
        "materialize_gcsim_full_team_probe_state",
        "materialize_gcsim_one_wearer_candidate",
    ),
    ".farming_response": (
        "RESPONSE_PROFILE_BASELINE",
        "RESPONSE_PROFILE_CONFIDENCE_OVERLAP",
        "RESPONSE_PROFILE_FAILED",
        "RESPONSE_PROFILE_IMMATERIAL",
        "RESPONSE_PROFILE_MATERIAL_NEGATIVE",
        "RESPONSE_PROFILE_MATERIAL_UPLIFT",
        "RESPONSE_PROFILE_MATERIALITY_UNRESOLVED",
        "RESPONSE_PROFILE_TIMEOUT",
        "RESPONSE_PROFILE_TOP",
        "RESPONSE_PROFILE_UNKNOWN_UNCERTAINTY",
        "RESPONSE_PROFILE_UNRESOLVED",
        "FarmingResponseSelectionError",
        "ResponseProfileAuditRow",
        "ResponseProfileOutcome",
        "ResponseProfileOutcomeStatus",
        "ResponseProfileSelectionBudget",
        "ResponseProfileSelectionResult",
        "select_wearer_response_profiles",
    ),
    ".farming_response_scan": (
        "GcsimResponseScanError",
        "GcsimResponseScanRequest",
        "GcsimResponseScanResult",
        "GcsimResponseScanSession",
        "GcsimResponseScanStatus",
        "run_gcsim_response_scan",
    ),
    ".farming_controller": (
        "GcsimFourPieceScreeningIssue",
        "GcsimFourPieceSearchError",
        "GcsimFourPieceSearchRequest",
        "GcsimFourPieceSearchResult",
        "GcsimFourPieceSearchSession",
        "GcsimFourPieceSearchStatus",
        "run_gcsim_four_piece_search",
    ),
    ".farming_advisor": (
        "GcsimFourPieceAdvisorError",
        "GcsimFourPieceAdvisorRequest",
        "GcsimFourPieceAdvisorResult",
        "GcsimFourPieceAdvisorSession",
        "GcsimFourPieceAdvisorStatus",
        "run_gcsim_four_piece_advisor",
    ),
    ".farming_layout_scan": (
        "GCSIM_GENERIC_MAIN_LAYOUT_SEED",
        "GcsimMainLayoutScanBudget",
        "GcsimMainLayoutScanError",
        "GcsimMainLayoutScanRequest",
        "GcsimMainLayoutScanResult",
        "GcsimMainLayoutScanSession",
        "GcsimMainLayoutScanStatus",
        "GcsimWearerLayoutSelection",
        "run_gcsim_main_layout_scan",
    ),
    ".farming_auto_advisor": (
        "GcsimAutomaticAdvisorError",
        "GcsimAutomaticAdvisorRequest",
        "GcsimAutomaticAdvisorResult",
        "GcsimAutomaticAdvisorSession",
        "GcsimAutomaticAdvisorStatus",
        "run_gcsim_automatic_four_piece_advisor",
    ),
    ".farming_finalist_optimizer": (
        "FinalistCompletionCallback",
        "GCSIM_FINALIST_OPTIMIZER_PROVENANCE_SCHEMA",
        "GcsimFinalistAttemptStatus",
        "GcsimFinalistOptimizerAttempt",
        "GcsimFinalistOptimizerBudget",
        "GcsimFinalistOptimizerError",
        "GcsimFinalistOptimizerOutcome",
        "GcsimFinalistOptimizerRequest",
        "GcsimFinalistOptimizerResult",
        "GcsimFinalistOptimizerSession",
        "GcsimFinalistOptimizerStatus",
        "GcsimOptimizedWearerAllocation",
        "OptimizerSessionFactory",
        "run_gcsim_finalist_optimizer",
    ),
    ".farming_optimized_advisor": (
        "AutomaticSessionFactory",
        "FinalistSessionFactory",
        "GcsimOptimizedAdvisorError",
        "GcsimOptimizedAdvisorRequest",
        "GcsimOptimizedAdvisorResult",
        "GcsimOptimizedAdvisorSession",
        "GcsimOptimizedAdvisorStatus",
        "run_gcsim_optimized_four_piece_advisor",
    ),
}

_LAZY_EXPORTS = {
    export_name: module_name
    for module_name, export_names in _LAZY_MODULE_EXPORTS.items()
    for export_name in export_names
}

__all__ = (*_LAZY_EXPORTS, "GitApplyPatchBackend")


def __getattr__(name: str) -> object:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
