# Manual cleanup of exact cache/research roots inspected on 2026-09-17.
# This is a bounded N0 recovery helper, not a general project/cache sweeper.
# Evidence: tests/fixtures/gcsim_optimizer_go_v1/generated_storage_audit_v1.json
# Preview is the default. -Apply requires explicit cleanup authorization.
# No logs/temp files are generated by this helper; output goes to the console.
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param([switch]$Apply, [switch]$Research, [switch]$Deep)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ($Research -and $Deep) { throw 'Choose one cleanup pass, not both.' }

$cleanupRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$cleanupPrefix = $cleanupRoot.TrimEnd('\') + '\'
if (-not (Test-Path -LiteralPath (Join-Path $cleanupRoot 'CODEX.md') -PathType Leaf) -or
    -not (Test-Path -LiteralPath (Join-Path $cleanupRoot 'run_workspace\gcsim\optimizer_go_selected.py') -PathType Leaf)) {
    throw 'This script must remain in the GenshinTeamsTracker tools directory.'
}

# Exact allowlist only. Never delete .codex_tmp, .go, or the project root itself.
$cleanupRelativePaths = @(
    '.go\build-cache',
    '.codex_tmp\support_replay_0016_go',
    '.codex_tmp\support_replay_0016_task_context_go',
    '.codex_tmp\go_cache_fanfare_v6_h',
    '.codex_tmp\go_cache',
    '.codex_tmp\go-cache-trace-provenance',
    '.codex_tmp\go-health-v5-20260824-d',
    '.codex_tmp\go_cache_fanfare_v6_f',
    '.codex_tmp\go-cache-trace-provenance-final',
    '.codex_tmp\go-cache-trace-provenance-verify',
    '.codex_tmp\go_cache_fanfare_v6_e'
)

if ($Research) {
    $review = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'optimizer_research_cleanup.json') -Raw | ConvertFrom-Json
    if ($review.schema_version -ne 1) { throw 'Unknown research cleanup schema.' }
    $cleanupRelativePaths = @($review.targets | ForEach-Object { $_.path.Replace('/', '\') })
    foreach ($relative in $cleanupRelativePaths) {
        if ($relative -notmatch '^\.codex_tmp\\[a-zA-Z0-9_-]+$' -or
            $relative -match '\\(all-sets-|jahoda-|selected-2plus2|history-design|gob10-|gob11-dependency-|gob11-gp3-)') {
            throw "Invalid or protected research allowlist entry: $relative"
        }
    }
    Write-Host ('Research pass: {0} reviewed directories, {1:N2} GiB at audit time.' -f
        $cleanupRelativePaths.Count, ($review.audited_target_bytes / 1GB))
}

if ($Deep) {
    $deepPlan = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'optimizer_deep_cleanup.json') -Raw | ConvertFrom-Json
    if ($deepPlan.schema_version -ne 1) { throw 'Unknown deep cleanup schema.' }
    $cleanupRelativePaths = @(@($deepPlan.delete_directories) + @($deepPlan.archive_directories) |
        ForEach-Object { $_.path.Replace('/', '\') })
    foreach ($relative in $cleanupRelativePaths) {
        if ($relative -notmatch '^(\.codex_tmp\\[^\\]+(\\[^\\]+)*|debug\\gcsim_[^\\]+|data\\gcsim\\engines\\(engines|failed)\\gcsim-[^\\]+)$' -or
            $relative.Contains('..') -or $relative -match '[*?]' -or
            $relative -match '^\.codex_tmp\\(history-design|gob10-performance-audit-worktree|v6_patch_index_20260824\.git|selected-2plus2-20260916|all-sets-install-20260917|all-sets-cli-20260917-run2|all-sets-review-20260917)(\\|$)') {
            throw "Invalid or protected deep cleanup target: $relative"
        }
    }
    Write-Host 'Deep pass: obsolete directories plus losslessly archived research evidence.'
}

function Assert-SafeCachePath([string]$CachePath) {
    $absolute = [System.IO.Path]::GetFullPath($CachePath)
    if (-not $absolute.StartsWith($cleanupPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Target is outside the project: $absolute"
    }
    $relative = $absolute.Substring($cleanupPrefix.Length)
    if ($cleanupRelativePaths -notcontains $relative) {
        throw "Target is not on the inspected cache allowlist: $absolute"
    }
    # Check the complete ancestor chain: Resolve-Path alone is not a junction guard.
    $ancestor = [System.IO.DirectoryInfo]::new($absolute)
    while ($null -ne $ancestor) {
        $ancestor.Refresh()
        if ($ancestor.Exists -and ($ancestor.Attributes -band [System.IO.FileAttributes]::ReparsePoint)) {
            throw "Refusing a linked/junction directory: $($ancestor.FullName)"
        }
        $ancestor = $ancestor.Parent
    }
    if ((Test-Path -LiteralPath $absolute) -and
        -not (Test-Path -LiteralPath $absolute -PathType Container)) {
        throw "Cache target is not a directory: $absolute"
    }
    return $absolute
}

function Assert-NoNestedDirectoryLinks([string]$CachePath) {
    $pending = [System.Collections.Generic.Stack[System.IO.DirectoryInfo]]::new()
    $pending.Push([System.IO.DirectoryInfo]::new($CachePath))
    while ($pending.Count -gt 0) {
        $current = $pending.Pop()
        $current.Refresh()
        if ($current.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
            throw "Refusing a linked/junction directory: $($current.FullName)"
        }
        foreach ($child in $current.EnumerateDirectories()) {
            $pending.Push($child)
        }
    }
}

function Assert-NoBuildInProgress {
    $busy = @(Get-Process -Name 'go', 'compile', 'link', 'gtt-optimizer', 'gtt-gcsim' -ErrorAction SilentlyContinue)
    if ($busy.Count -gt 0) {
        $description = ($busy | ForEach-Object { '{0} (PID {1})' -f $_.ProcessName, $_.Id }) -join ', '
        throw "Close running builds/optimizer/simulations before cleanup: $description"
    }
}

function Assert-NoRuntimeOrWorktreeDependency([string[]]$Targets) {
    $worktrees = @(& git -C $cleanupRoot worktree list --porcelain)
    if ($LASTEXITCODE -ne 0) { throw 'Cannot verify registered Git worktrees.' }
    $references = @($worktrees | Where-Object { $_.StartsWith('worktree ') } | ForEach-Object { $_.Substring(9) })
    $engineStore = Join-Path $cleanupRoot 'data\gcsim\engines'
    $activePath = Join-Path $engineStore 'active_engine.json'
    if (Test-Path -LiteralPath $activePath) {
        $active = Get-Content -LiteralPath $activePath -Raw | ConvertFrom-Json
        foreach ($engineId in @($active.active_engine_id, $active.rollback_engine_id)) {
            if (-not $engineId) { continue }
            $references += Join-Path $engineStore ('engines\{0}' -f $engineId)
            $overlay = Join-Path $engineStore ('engines\{0}\build\gtt-source-overlay.json' -f $engineId)
            if (Test-Path -LiteralPath $overlay) {
                $mapping = (Get-Content -LiteralPath $overlay -Raw | ConvertFrom-Json).Replace
                foreach ($property in $mapping.PSObject.Properties) {
                    $references += $property.Name
                    $references += [string]$property.Value
                }
            }
        }
    }
    if ($Deep) {
        foreach ($engineId in $deepPlan.protected_diagnostic_engines) {
            $references += Join-Path $engineStore ('engines\{0}' -f $engineId)
        }
    }
    foreach ($target in $Targets) {
        $prefix = $target.TrimEnd('\') + '\'
        foreach ($reference in $references) {
            $absoluteReference = [System.IO.Path]::GetFullPath($reference.Replace('/', '\'))
            if ($absoluteReference.Equals($target, [System.StringComparison]::OrdinalIgnoreCase) -or
                $absoluteReference.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                throw "Protected worktree or active/rollback overlay depends on cleanup target: $absoluteReference"
            }
        }
    }
}

$cleanupTargets = @()
foreach ($relative in $cleanupRelativePaths) {
    $absolute = Assert-SafeCachePath (Join-Path $cleanupRoot $relative)
    if (Test-Path -LiteralPath $absolute -PathType Container) {
        $cleanupTargets += $absolute
    } else {
        Write-Host "Already absent: $absolute"
    }
}

Write-Host "Project: $cleanupRoot"
Write-Host "Inspected directories present: $($cleanupTargets.Count)"
foreach ($absolute in $cleanupTargets) { Write-Host "  $absolute" }
Write-Host 'Account data, assets, current results and protected engines are NOT deletion targets.'
Assert-NoRuntimeOrWorktreeDependency $cleanupTargets

if (-not $Apply) {
    Write-Host 'PREVIEW ONLY: nothing was deleted. Add -Apply to delete only these reviewed paths permanently.'
    return
}

Assert-NoBuildInProgress
# Validate every subtree before deleting any target; never follow directory links.
foreach ($absolute in $cleanupTargets) {
    Write-Host "Checking: $absolute"
    Assert-NoNestedDirectoryLinks $absolute
}

if ($Deep -and $cleanupTargets.Count -gt 0 -and -not $WhatIfPreference) {
    $archiveHelper = Join-Path $PSScriptRoot 'archive_optimizer_evidence.py'
    $projectPython = Join-Path $cleanupRoot '.venv\Scripts\python.exe'
    $archivePath = Join-Path $cleanupRoot $deepPlan.archive_path
    if (-not (Test-Path -LiteralPath $archivePath)) {
        & $projectPython $archiveHelper
        if ($LASTEXITCODE -ne 0) { throw 'Evidence archive preparation failed; nothing deleted.' }
    }
    & $projectPython $archiveHelper --verify
    if ($LASTEXITCODE -ne 0) { throw 'Evidence archive/source verification failed; nothing deleted.' }
    Assert-NoBuildInProgress
    Assert-NoRuntimeOrWorktreeDependency $cleanupTargets
}

$removedCount = 0
foreach ($absolute in $cleanupTargets) {
    Assert-NoBuildInProgress
    $checkedPath = Assert-SafeCachePath $absolute
    if ($PSCmdlet.ShouldProcess($checkedPath, 'Permanently delete inspected disposable data')) {
        Write-Host "Removing: $checkedPath"
        Remove-Item -LiteralPath $checkedPath -Recurse -Force -ErrorAction Stop
        $removedCount++
        Write-Host "Removed: $checkedPath"
    }
}
Write-Host "Finished. Removed directories: $removedCount."
if ($Deep) {
    Write-Host 'Archived witnesses are recoverable from the verified ZIP. Unarchived obsolete generated outputs require regeneration.'
} else {
    Write-Host 'This was not a full scratch-directory purge. Caches can be regenerated; old raw research output needs rerunning its experiment.'
}
