from __future__ import annotations

# Deprecated compatibility facade. New production imports should use ui.right_panel.*.

from localization import tr
from ui.utils.tooltips import install_custom_tooltip
from ui.right_panel.common.metrics import (
    ABYSS_CHAMBER_BADGE_WIDTH,
    ABYSS_CHAMBER_GRID_SPACING,
    ABYSS_DPS_COLUMN_MIN_WIDTH,
    ABYSS_FACT_DPS_LEFT_BUDGET_MAX,
    ABYSS_TIMER_CELL_WIDTH,
    ABYSS_TIMER_ELAPSED_WIDTH,
    ABYSS_TIMER_FRAME_WIDTH,
    ABYSS_TIMER_SEPARATOR_WIDTH,
    ABYSS_TIMER_SEGMENT_WIDTH,
    BONUS_MEMBER_ICON_SIZE,
    RIGHT_PANEL_PROTOTYPE_CONTENT_MIN_WIDTH,
    RIGHT_PANEL_PROTOTYPE_MIN_WIDTH,
    SLOT_BADGE_HEIGHT,
    SLOT_BUILD_BONUS_FEATHER,
    SLOT_CARD_FIXED_HEIGHT,
    SLOT_CARD_MARGIN,
    SLOT_CARD_WIDTH,
    SLOT_CLUSTER_WIDTH,
    SLOT_DRAG_MIME_TYPE,
    SLOT_EQUIP_BOX_SIZE,
    SLOT_EQUIP_ICON_SIZE,
    SLOT_NAME_HEIGHT,
    SLOT_PORTRAIT_SIZE,
    SLOT_TOP_SPACING,
    SLOT_WARNING_BADGE_WIDTH,
    SLOT_WEAPON_ICON_SIZE,
    _BONUS_MEMBER_SIDE_ICON_PIXMAP_CACHE,
    _BONUS_SOURCE_ICON_PIXMAP_CACHE,
    _FIT_PIXMAP_CACHE,
    _fit_pixmap,
)
from ui.right_panel.common.slot_card import (
    BuildMiniSetStackWidget,
    RightPanelSlotCardWidget,
    _build_mini_set_stack_pixmap,
)
from ui.right_panel.common.team_card import RightPanelTeamCardWidget
from ui.right_panel.live_run.panel import (
    BonusSourceChipWidget,
    BonusSourceStripWidget,
    ChamberTableBlockWidget,
    ChamberTimerCellWidget,
    CompactAbyssTimerWidget,
    DetailRowWidget,
    RunModeTabsWidget,
    RightPanelRunActionsWidget,
    RunRightPanelWidget,
    SelectedCharacterDetailsWidget,
    _bonus_member_side_icon_pixmap,
    _bonus_source_icon_pixmap,
    _bonus_source_tooltip_html,
    make_mode_tab_button,
    right_panel_stylesheet,
)

# Old Prototype names remain supported temporarily.
RightPanelPrototypeWidget = RunRightPanelWidget
RightPanelSlotPrototypeWidget = RightPanelSlotCardWidget
RightPanelTeamPrototypeWidget = RightPanelTeamCardWidget

__all__ = [
    "ABYSS_CHAMBER_BADGE_WIDTH",
    "ABYSS_CHAMBER_GRID_SPACING",
    "ABYSS_DPS_COLUMN_MIN_WIDTH",
    "ABYSS_FACT_DPS_LEFT_BUDGET_MAX",
    "ABYSS_TIMER_CELL_WIDTH",
    "ABYSS_TIMER_ELAPSED_WIDTH",
    "ABYSS_TIMER_FRAME_WIDTH",
    "ABYSS_TIMER_SEPARATOR_WIDTH",
    "ABYSS_TIMER_SEGMENT_WIDTH",
    "BONUS_MEMBER_ICON_SIZE",
    "BuildMiniSetStackWidget",
    "BonusSourceChipWidget",
    "BonusSourceStripWidget",
    "ChamberTableBlockWidget",
    "ChamberTimerCellWidget",
    "CompactAbyssTimerWidget",
    "DetailRowWidget",
    "RIGHT_PANEL_PROTOTYPE_CONTENT_MIN_WIDTH",
    "RIGHT_PANEL_PROTOTYPE_MIN_WIDTH",
    "RightPanelPrototypeWidget",
    "RightPanelRunActionsWidget",
    "RightPanelSlotCardWidget",
    "RightPanelSlotPrototypeWidget",
    "RightPanelTeamCardWidget",
    "RightPanelTeamPrototypeWidget",
    "RunModeTabsWidget",
    "RunRightPanelWidget",
    "SelectedCharacterDetailsWidget",
    "SLOT_BADGE_HEIGHT",
    "SLOT_BUILD_BONUS_FEATHER",
    "SLOT_CARD_FIXED_HEIGHT",
    "SLOT_CARD_MARGIN",
    "SLOT_CARD_WIDTH",
    "SLOT_CLUSTER_WIDTH",
    "SLOT_DRAG_MIME_TYPE",
    "SLOT_EQUIP_BOX_SIZE",
    "SLOT_EQUIP_ICON_SIZE",
    "SLOT_NAME_HEIGHT",
    "SLOT_PORTRAIT_SIZE",
    "SLOT_TOP_SPACING",
    "SLOT_WARNING_BADGE_WIDTH",
    "SLOT_WEAPON_ICON_SIZE",
    "_BONUS_MEMBER_SIDE_ICON_PIXMAP_CACHE",
    "_BONUS_SOURCE_ICON_PIXMAP_CACHE",
    "_FIT_PIXMAP_CACHE",
    "_bonus_member_side_icon_pixmap",
    "_bonus_source_icon_pixmap",
    "_bonus_source_tooltip_html",
    "_build_mini_set_stack_pixmap",
    "_fit_pixmap",
    "install_custom_tooltip",
    "make_mode_tab_button",
    "right_panel_stylesheet",
    "tr",
]
